# Default values for nft-web-components.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 787579592221.dkr.ecr.us-east-1.amazonaws.com/nft-web-components
